apiVersion: v1
kind: Service
metadata:
  name: otoprod
  labels:
    run: otoprod
spec:
  ports:
    - port: 5000 
      targetPort: 5000
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: otoprod
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: otoprod
    spec:
      containers:
      - name: otoprod
        image: otomato/oto-products:BUILD_NUMBER
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
